name: Union Config
description: Apply Union configuration to the dataplane cluster.

inputs:
  manifest:
    description: Union Team Service Accounts manifest file path, relative to the repository root.
    required: true
  environment:
    description: Target environment (e.g. dev, prod).
    required: true
    default: prod

runs:
  using: composite
  steps:
    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v3
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.environment == 'prod' && 'projects/430580391891/locations/global/workloadIdentityPools/ci-dataplattform/providers/ci-dataplattform' || 'projects/483437874962/locations/global/workloadIdentityPools/ci-dataplattform/providers/ci-dataplattform' }}
        service_account: um-${{ github.event.repository.name }}@nav-data-union-restricted-${{ inputs.environment }}.iam.gserviceaccount.com
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        install_components: gke-gcloud-auth-plugin

    - name: Get cluster credentials 
      shell: bash
      run: |
        gcloud container fleet memberships get-credentials \
          "${{ inputs.environment }}-union-restricted" \
          --project "nav-data-union-control-${{ inputs.environment }}"

    - name: Apply Union Team Service Accounts manifest
      shell: bash
      run: |
        kubectl apply -f "${{ inputs.manifest }}"
